config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root "category#index"
  resources "category" do
    resources :post, only: [:show]
  end
  get '/tintuc' => 'category#tintuc'
  get '/gioithieu' => 'category#gioithieu'
  get '/video' => 'category#video'
  get '/khachhang' => 'category#khachhang'
  get '/tatca' => 'category#tatca'
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :posts
    validates :name, presence: true, length: { maximum: 50 }
	validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :category
    has_attached_file :image, :styles => { :medium => "680x300>", :thumb => "170x75>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    validates :title, presence: true, length: { maximum: 50 }
	validates :content, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.all
    @posts = Post.all
    
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
  	@posts = @category.posts
  end
  
  def tintuc
  	@categories = Category.all
  	@posts = Post.all
  end
  def gioithieu
  	@categories = Category.all
  	@posts = Post.all
  end
  def khachhang
  	@categories = Category.all
  	@posts = Post.all
  end
  def video
  	@categories = Category.all
  	@posts = Post.all
  end
  def tatca
  	@categories = Category.all
  	@posts = Post.all
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def show
    category = Category.find(params[:category_id])
  	@post = Post.find(params[:id])
  	@posts = category.posts
  	@category = Category.find(params[:category_id])
  	@categories = Category.all
  	@posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/category/gioithieu.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
	<div class="w3-container w3-padding-jumpo">
		<%= render partial: "shared/sidebar" %>
	</div>
</div>	
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/category/index.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
	<div class="w3-container w3-padding-jumpo">
		<%= render partial: "shared/sidebar" %>
		<div class="w3-col l9 m9 s12">
			<div class="w3-container">
				<img class="mySlides" src="https://s3.amazonaws.com/froala/temp_files%2F1460402779063-berkey-water-home-family.jpg" style="width:100%">
				
				<img class="mySlides" src="https://s3.amazonaws.com/froala/temp_files%2F1460399358103-040616_HP_Hero_StaGreen_cp+-+Copy+%282%29+-+Copy.jpg" style="width:100%">
			</div><br>
			<div style="margin-bottom:30px" class="w3-container   w3-padding-jumpo">
				<div class="w3-container"><button style="background:rgb(41, 105, 176);float:right" class="w3-btn"><%= link_to tatca_path do %>Xem Tất Cả SP <i class="fa fa-chevron-right" aria-hidden="true"></i><i class="fa fa-chevron-right" aria-hidden="true"></i><% end %></button></div>
				<% @posts.where('category_id = 2').limit(8).each do |post| %>	
						<%= link_to [post.category, post] do %>
							<div class="w3-padding  w3-col l4 m6">
								<div  class="w3-card-1 w3-hover-shadow w3-border-bottom">
									<img src="http://www.maylocnuockarofi.com.vn/uploads/images/may-loc-nuoc-karofi/210x140-01.jpg" style="width:100%">
									<div style="min-height:160px" class="w3-white w3-round w3-container">
										<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= post.title %></span></span></strong></p>
					
										<p><strong><span style="color: rgb(184, 49, 47);">Gi&aacute;: Li&ecirc;n hệ</span></strong></p>
									</div>
								</div>
							</div>	
						<% end %>	
				<% end %>
			</div>
			
			<div class="w3-white w3-margin w3-padding  w3-container">
				<button style="background:rgb(41, 105, 176);float:right" class="w3-btn"><%= link_to khachhang_path do %>Xem Tất Cả <i class="fa fa-chevron-right" aria-hidden="true"></i><i class="fa fa-chevron-right" aria-hidden="true"></i><% end %></button>
				<h1>Khách Hàng Đánh Giá</h1>
				
				<div class="w3-row w3-margin">
					<div class="w3-round w3-third">
	  					<img class="w3-round " src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQIizroaSVebmjA1NoRto8JomJkpAmpLxWXEgZ7uiv7LHm7P1OMCQ" style="width:100%;">
					</div>
					<div class="w3-twothird w3-container">
					  <h2>Anh Nguyễn Trần ...</h2>
					  <p>
					  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
					  </p>
					</div>
				</div><hr>
				<div class="w3-row w3-margin">
					<div class="w3-third">
	  					<img class="w3-round " src="http://evelynsandoval.pw/wp-content/uploads/2015/07/Collect-Customer-Feedback-for-Marketing.jpg" style="width:100%;">
					</div>
					<div class="w3-twothird w3-container">
					  <h2>Chị Lê Thị Something</h2>
					  <p>
					  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
					  </p>
					</div>
				</div>	
					
			</div>
			
			<div class="w3-white w3-margin w3-padding  w3-container">
				<button style="background:rgb(41, 105, 176);float:right" class="w3-btn"><%= link_to tintuc_path do %>Xem Tất Cả <i class="fa fa-chevron-right" aria-hidden="true"></i><i class="fa fa-chevron-right" aria-hidden="true"></i><% end %></button>
				<h1>Tin Tức</h1>
				<div class="w3-row w3-margin">
					<div class="w3-third">
	  					<img src="http://www.maylocnuockarofi.com.vn/uploads/images/may-loc-nuoc-karofi/210x140-01.jpg" style="width:100%;">
					</div>
					<div class="w3-twothird w3-container">
					  <h2>5 Terre</h2>
					  <p>
					  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
					  </p>
					</div>
				</div><hr>
				<div class="w3-row w3-margin">
					<div class="w3-third">
	  					<img src="http://www.maylocnuockarofi.com.vn/uploads/images/may-loc-nuoc-karofi/210x140-01.jpg" style="width:100%;">
					</div>
					<div class="w3-twothird w3-container">
					  <h2>5 Terre</h2>
					  <p>
					  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
					  </p>
					</div>
				</div>	
					
			</div>
			
		</div>
	</div>
</div><br><br>

app/views/category/khachhang.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
	<div class="w3-container w3-padding-jumpo">
		<%= render partial: "shared/sidebar" %>
	</div>
</div>	
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/category/show.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
	<div class="w3-container w3-padding-jumpo">
		<%= render partial: "shared/sidebar" %>
		
		<div class="w3-col l9 m9 s12">
			<div style="margin-bottom:30px" class="w3-container w3-padding-jumpo">
				<% @posts.each do |post| %>	
						<%= link_to [post.category, post] do %>
							<div class="w3-padding  w3-col l4 m6">
								<div  class="w3-card-1 w3-border-bottom">
									<img src="http://www.maylocnuockarofi.com.vn/uploads/images/may-loc-nuoc-karofi/210x140-01.jpg" style="width:100%">
									<div style="min-height:160px" class="w3-white w3-round w3-container">
										<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= post.title %></span></span></strong></p>
					
										<p><strong><span style="color: rgb(184, 49, 47);">Gi&aacute;: Li&ecirc;n hệ</span></strong></p>
									</div>
								</div>
							</div>	
						<% end %>	
				<% end %>
			</div>
		</div>
	</div>
</div><br><br>


<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/category/tatca.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
	<div class="w3-container w3-padding-jumpo">
		<%= render partial: "shared/sidebar" %>
	</div>
</div>	
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/category/tintuc.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
	<div class="w3-container w3-padding-jumpo">
		<%= render partial: "shared/sidebar" %>
		
		
		<div class="w3-col l9 m9 s12">
			<div class="w3-padding  w3-container">
	
	<div class="w3-container w3-white w3-padding">
		<h1>Tin Tức</h1>
		<% @posts.where('category_id = 2').limit(8).each do |post| %>	
			<%= link_to [post.category, post] do %>
        		<div class="w3-border-bottom w3-container">
        			<div class="w3-col l4 m4 s12 w3-padding">
        				<img class=" w3-round" src="http://www.maylocnuockarofi.com.vn/uploads/images/may-loc-nuoc-karofi/210x140-01.jpg" style="width:100%">	
        			</div>
        			
        			<div class="  w3-col l8 m8 s12">
        				<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= post.title %></span></span></strong></p>	
        				<p>dsadasdasdasdasdasdas</p>
        				
        			</div>
        		</div><br>
			<% end %>	
		<% end %>
	</div>	
</div>
	</div>
	</div>
</div>			
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/category/video.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
	<div class="w3-container w3-padding-jumpo">
		<%= render partial: "shared/sidebar" %>
	</div>
</div>	
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta charset="utf-8">
  <meta content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" name="viewport">
  <%= csrf_meta_tags %>
  <!-- Google Maps -->


</head>
<body style="background:#DEDEDD">
<%= render partial: "shared/header" %>
  <%= yield %>
<%= render partial: "shared/footer" %>

<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";  
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}    
    x[myIndex-1].style.display = "block";  
    setTimeout(carousel, 2000);    
}
</script>
<script>
function w3_open() {
    document.getElementsByClassName("w3-sidenav")[0].style.width = "300px";
    document.getElementsByClassName("w3-sidenav")[0].style.textAlign = "center";
    document.getElementsByClassName("w3-sidenav")[0].style.fontSize = "40px";
    document.getElementsByClassName("w3-sidenav")[0].style.paddingTop = "10%";
    document.getElementsByClassName("w3-sidenav")[0].style.display = "block";
}
function w3_close() {
    document.getElementsByClassName("w3-sidenav")[0].style.display = "none";
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else { 
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

</body>
</html>

app/views/post/show.html.erb
<div class="w3-main" style="margin:auto;max-width:1260px">
    <div class="w3-container w3-padding-jumpo">
        <%= render partial: "shared/sidebar" %>
        
        <div class="w3-col l9 m9 s12 w3-padding">
            <div style="margin-bottom:30px" class="w3-white w3-container  w3-padding">
                <h1>Sản Phẩm</h1>
                <div class="w3-padding w3-col s6 m6">
                    <img src="http://images.lowes.com/product/converted/084691/084691808169lg.jpg" style="width:100%">
                </div>
                <div class="w3-col s6 m6">
                    <p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= @post.title %></span></span></strong></p>
                    <p><strong><span style="color: rgb(184, 49, 47);"><span style="font-size: 18px;">Tiêu Chuẩn</span></span></strong></p>
                    <p><strong><span style="color: rgb(243, 121, 52);"><span style="font-size: 18px;"><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i></span></span></strong></p>
                    <div class="w3-container">
                        <img src="http://www.iso.org/iso/2012_iso-logo_print.png" style="width:20%">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/7/73/Energy_Star_logo.svg" style="width:20%">
                    </div>
                </div>
            </div>
            
            <div style="margin-bottom:30px" class="w3-white w3-container  w3-padding">
                <%= raw @post.content %>	
            </div>
            <div style="margin-bottom:30px" class="w3-white w3-container  w3-padding">
                <h3>Các Sản Phẩm Cùng Loại</h3>
                <% @posts.each do |post| %>	
						<%= link_to [post.category, post] do %>
							<div class="w3-padding  w3-col l4 m6 ">
								<div  class="w3-card-1 w3-border-bottom">
									<img src="http://www.maylocnuockarofi.com.vn/uploads/images/may-loc-nuoc-karofi/210x140-01.jpg" style="width:100%">
									<div style="min-height:160px" class="w3-white w3-round w3-container">
										<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= post.title %></span></span></strong></p>
										<p><strong><span style="color: rgb(184, 49, 47);">Gi&aacute;: Li&ecirc;n hệ</span></strong></p>
									</div>
								</div>
							</div>	
						<% end %>	
				<% end %>	
            </div>
        </div>
    </div>
</div>    
<script>
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>

app/views/shared/_footer.html.erb
<footer>
	 <div class="w3-display-container w3-animate-opacity">
	    <%= image_tag "7-Water-Heart-Love-Wallpapers-HD", style: "width:100%;min-height:350px;max-height:680px;" %>
	    <div class="w3-round w3-container w3-display-bottomleft  w3-margin" style="color:white;background:#0b5394;opacity:0.6">  
			<h1>Công Ty CPTM Môi Trường Việt</h1>
			<h3><i class="fa fa-phone"></i> 09087668888</h3>
			<h3><i class="fa fa-map-marker"></i> 26, Nguyễn Sỹ Sách, TP.Vinh</h3>
			<a class="w3-btn-floating w3-teal" href="javascript:void(0)" title="Facebook"><i class="fa fa-facebook"></i></a>
  <a class="w3-btn-floating w3-teal" href="javascript:void(0)" title="Twitter"><i class="fa fa-twitter"></i></a>
  <a class="w3-btn-floating w3-teal" href="javascript:void(0)" title="Google +"><i class="fa fa-google-plus"></i></a>
  <a class="w3-btn-floating w3-teal w3-hide-small" href="javascript:void(0)" title="Linkedin"><i class="fa fa-linkedin"></i></a>
	    </div>
	    
	</div>
	
	
</footer>

app/views/shared/_header.html.erb
<!-- Navbar -->
<div style="color:white;background:#0b5394;opacity:0.8" class="w3-top">
 <ul class="w3-navbar w3-theme-d2 w3-left-align w3-large">
  <li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
    <a class="w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
  </li>
  <li><a href="https://moitruongviet-chaprynz.c9users.io" class="w3-teal"><i class="fa fa-home w3-margin-right"></i>MoitruongAsia</a></li>
  <li class="w3-hide-small"><%= link_to gioithieu_path do %>Giới Thiệu Về Công Ty<% end %></li>
  <li class="w3-hide-small"><%= link_to tintuc_path do %>Tin Tức Liên Quan<% end %></li>
  <li class="w3-hide-small w3-right"><a href="#" class="w3-hover-teal" title="Search"><i class="fa fa-search"></i></a></li>
 </ul>
</div>


<!-- Navbar on small screens -->
<div id="navDemo" class="w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:43px;">
  <ul style="color:white;background:#0b5394;opacity:0.96" class="w3-navbar w3-left-align w3-large w3-theme">
    <li><%= link_to gioithieu_path do %>Giới Thiệu Về Công Ty<% end %></li>
    <li><%= link_to tintuc_path do %>Tin Tức Liên Quan<% end %></li>
    <li><a href="#"><i class="fa fa-search"></i></a></li>
  </ul>
</div>

<div class="w3-display-container w3-animate-opacity">
  <%= image_tag "refinery-at-night.jpg", style: "width:100%;min-height:350px;max-height:600px;" %>
  <div class="w3-round w3-container w3-display-bottomleft  w3-margin" style="color:white;background:#0b5394;opacity:0.6">  
    <h1>Công Ty CPTM Môi Trường Việt</h1>
    <h3><i class="fa fa-phone"></i> 09087668888</h3>
    <h3><i class="fa fa-map-marker"></i> 26, Nguyễn Sỹ Sách, TP.Vinh</h3>
  </div>
</div><br>

app/views/shared/_sidebar.html.erb
<div class="w3-col l3 m3 s12" style="margin-bottom:20px">
			<div class="w3-card-1 w3-topbar w3-border-blue">
				<div class="w3-container w3-white ">
					<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;">Danh Mục Sản Phẩm</span></span></strong></p>
				</div>
				<% @categories.each do |category| %>
					<div class="w3-container active w3-border-bottom w3-pale-blue ">
							<p><strong><span style="color: rgb(184, 49, 47);"><span style="font-size: 18px;"><%= link_to category, class: "w3-hover-text-blue" do %><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> <%= category.name %><% end %></span></span></strong></p>
						</div>	
				<% end %>
				<div class="w3-container w3-border-bottom w3-pale-blue ">
					<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= link_to tatca_path, class: "w3-hover-text-blue" do %><i class="fa fa-plus-circle" aria-hidden="true"></i> Xem Tất Cả SP<% end %></span></span></strong></p>
				</div>
				<div class="w3-container w3-border-bottom w3-pale-blue ">
					<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= link_to khachhang_path, class: "w3-hover-text-blue" do %><i class="fa fa-home" aria-hidden="true"></i> Khách hàng & Các dự án <% end %></span></span></strong></p>
				</div>
				<div class="w3-container w3-border-bottom w3-pale-blue ">
					<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= link_to tintuc_path, class: "w3-hover-text-blue" do %><i class="fa fa-newspaper-o" aria-hidden="true"></i> Tin Tức<% end %></span></span></strong></p>
				</div>
				<div class="w3-container w3-border-bottom w3-pale-blue ">
					<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><i class="fa fa-phone-square" aria-hidden="true"></i> Liên Hệ</span></span></strong></p>
					<p><strong><span style="color: rgb(184, 49, 47);"><span style="font-size: 18px;">09.087.668. 888</span></span></strong></p>
					<p><strong><span style="color: rgb(184, 49, 47);"><span style="font-size: 18px;"><i class="fa fa-map-marker"></i> 26, Nguyễn Sỹ Sách, TP.Vinh</span></span></strong></p>
					<%= link_to "https://www.facebook.com/ydt.nguyen" do %><p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><i class="fa fa-facebook-official" aria-hidden="true"></i> Facebook</span></span></strong></p><% end %>	
				</div>
				<div class="w3-container w3-border-bottom w3-pale-blue ">
					<p><strong><span style="color: rgb(41, 105, 176);"><span style="font-size: 18px;"><%= link_to video_path, class: "w3-hover-text-blue" do %><i class="fa fa-youtube-square" aria-hidden="true"></i> Video<% end %></span></span></strong></p>
				</div>
			</div>	
		</div>
		